name: Deploy api

on:
  push:
    branches:
      - main
    paths:
      - "packages/api/**"

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Build
        working-directory: ./packages/api
        run: bun install

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN}}
          accountId: 3b717be6e2f2de3a68218e2e52836b84
          projectName: "test-app"
          workingDirectory: ./packages/api

      # - name: Publish to Cloudflare Pages
      #   with:
      # - name: hello world
      #   run: echo "Hello world"
      #   shell: bash

  # goodbye:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: goodbye world
  #       run: echo "Goodbye world"
  #       shell: bash
